# Generated by Django 2.2 on 2019-10-09 20:37

import apps.libra.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(max_length=150)),
                ('birth_date', models.DateField(verbose_name='Date of Birth')),
                ('sex', models.NullBooleanField(choices=[(None, ''), (True, 'Female'), (False, 'Male')])),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publish_date', models.PositiveSmallIntegerField(default=2019, null=True, validators=[django.core.validators.MinValueValidator(400), apps.libra.models.max_value_current_year])),
                ('isbn_code', models.CharField(max_length=25, null=True, unique=True)),
                ('author', models.ManyToManyField(related_name='author_books', to='libra.Author')),
                ('genre', models.ForeignKey(on_delete=models.SET('unknown'), related_name='genre_books', to='libra.Genre')),
            ],
        ),
    ]
