# Generated by Django 2.2 on 2019-10-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libra', '0004_auto_20191011_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=models.SET(None), related_name='genre_books', to='libra.Genre'),
        ),
    ]
